In [8]:
#Mean and Standard Deviation

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
std_deviation = np.std(arr)
print("Mean:", mean)
print("Standard Deviation:", std_deviation)

Mean: 3.0
Standard Deviation: 1.4142135623730951


In [7]:
#5x5 Matrix

print("Random Matrix:")
print(random_matrix)
min_row_values = np.min(random_matrix, axis=1)
max_row_values = np.max(random_matrix, axis=1)
print("\nMinimum values along each row:")
print(min_row_values)
print("\nMaximum values along each row:")
print(max_row_values)
min_col_values = np.min(random_matrix, axis=0)
max_col_values = np.max(random_matrix, axis=0)
print("\nMinimum values along each column:")
print(min_col_values)
print("\nMaximum values along each column:")
print(max_col_values)


Random Matrix:
[[0.09844601 0.73891495 0.3361915  0.64752623 0.32651904]
 [0.87549833 0.04277114 0.70430932 0.46289867 0.590474  ]
 [0.04108246 0.22862836 0.18784961 0.53295932 0.55719469]
 [0.44622866 0.2831521  0.70324731 0.62600683 0.36322471]
 [0.81128413 0.19851963 0.83275393 0.08557572 0.75165828]]

Minimum values along each row:
[0.09844601 0.04277114 0.04108246 0.2831521  0.08557572]

Maximum values along each row:
[0.73891495 0.87549833 0.55719469 0.70324731 0.83275393]

Minimum values along each column:
[0.04108246 0.04277114 0.18784961 0.08557572 0.32651904]

Maximum values along each column:
[0.87549833 0.73891495 0.83275393 0.64752623 0.75165828]


In [6]:
#Cosine Similarity Function

def cos_similarity(vector1, vector2):
  
    dot_product = np.dot(vector1, vector2)
    vector_1 = np.linalg.norm(vector1)
    vector_2 = np.linalg.norm(vector2)
    
    cos_sim = dot_product / (vector_1 * vector_2)
    
    return cos_sim

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

print("Cos Similarity:", cos_similarity(vector1, vector2))

Cos Similarity: 0.9746318461970762
